# Generated by Django 5.2.3 on 2025-07-21 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('study_modality', models.CharField(choices=[('virtual', 'Virtual'), ('presential', 'Presential')], default='presential', max_length=50)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('V', 'Cédula Venezolana (V)'), ('CC', 'Cédula Colombiana (CC)')], default='V', max_length=2)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('progenitor_name', models.CharField(max_length=50)),
                ('progenitor_document_number', models.CharField(max_length=20, unique=True)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='H', max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('topic_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidades',
            },
        ),
        migrations.AlterModelOptions(
            name='calendario',
            options={'verbose_name': 'Evento de calendario', 'verbose_name_plural': 'Eventos de calendario'},
        ),
        migrations.AlterModelOptions(
            name='cedula',
            options={'verbose_name': 'Cédula', 'verbose_name_plural': 'Cédulas'},
        ),
        migrations.AlterField(
            model_name='calendario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='tipo_documento',
            field=models.CharField(choices=[('V', 'Cédula Venezolana (V)'), ('CC', 'Cédula Colombiana (CC)')], default='V', max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterModelTable(
            name='calendario',
            table='calendario',
        ),
        migrations.AlterModelTable(
            name='cedula',
            table='cedulas',
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Group_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.levels')),
            ],
            options={
                'verbose_name': 'Grupo de curso',
                'verbose_name_plural': 'Grupos de cursos',
                'db_table': 'grupos_cursos',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Grade_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observations', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
            options={
                'verbose_name': 'Nota de estudiante',
                'verbose_name_plural': 'Notas de estudiantes',
                'db_table': 'notas_estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('percentage_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_position', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutores',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tutors'),
        ),
    ]
