# Generated by Django 5.2.3 on 2025-08-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
