# Generated by Django 5.1.7 on 2025-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250419_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='calendario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='tipo_documento',
            field=models.CharField(choices=[('V', 'Cédula Venezolana (V)'), ('CC', 'Cédula Colombiana (CC)')], default='V', max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
