# Generated by Django 5.2.3 on 2025-08-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='correo',
        ),
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
