# Generated by Django 5.2.3 on 2025-08-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_correo_alter_user_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='period',
        ),
        migrations.AddField(
            model_name='courses',
            name='cohort',
            field=models.IntegerField(blank=True, help_text='Cohorte del Curso', null=True, unique=True),
        ),
    ]
