# Generated by Django 5.2.3 on 2025-08-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_courses_period_courses_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='progenitor_document_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='progenitor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
