# Generated by Django 5.2.3 on 2025-08-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_apellido_remove_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='staff_position',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('coordinator', 'Coordinator')], default='tutor', max_length=50),
        ),
    ]
