# Generated by Django 5.2.3 on 2025-08-08 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tutors_staff_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tutors'),
        ),
    ]
