# Generated by Django 5.2.3 on 2025-08-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_todoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelTable(
            name='todoitem',
            table='tareas',
        ),
    ]
