# Generated by Django 5.2.3 on 2025-08-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_todoitem_options_alter_todoitem_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='cohort',
        ),
        migrations.AddField(
            model_name='group_levels',
            name='cohort',
            field=models.IntegerField(blank=True, help_text='Cohorte del Grupo', null=True),
        ),
    ]
