# Generated by Django 5.2.3 on 2025-08-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_courses_cohort_group_levels_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Venezolana', 'Venezolana'), ('Colombiana', 'Colombiana'), ('Argentina', 'Argentina'), ('Boliviana', 'Boliviana'), ('Brasileña', 'Brasileña'), ('Chilena', 'Chilena'), ('Costarricense', 'Costarricense'), ('Cubana', 'Cubana'), ('Dominicana', 'Dominicana'), ('Ecuatoriana', 'Ecuatoriana'), ('Salvadoreña', 'Salvadoreña'), ('Española', 'Española'), ('Estadounidense', 'Estadounidense'), ('Guatemalteca', 'Guatemalteca'), ('Hondureña', 'Hondureña'), ('Mexicana', 'Mexicana'), ('Nicaragüense', 'Nicaragüense'), ('Panameña', 'Panameña'), ('Paraguaya', 'Paraguaya'), ('Peruana', 'Peruana'), ('Puertorriqueña', 'Puertorriqueña'), ('Uruguaya', 'Uruguaya'), ('Otra', 'Otra')], max_length=50, null=True),
        ),
    ]
