# Generated by Django 5.2.3 on 2025-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_person_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='students',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='study_modality',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], default='presential', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='H', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='staff_position',
            field=models.CharField(choices=[('profesor', 'Profesor'), ('tutor', 'Tutor'), ('administrador', 'Administrador')], default='tutor', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('tutor', 'Tutor'), ('admin', 'Administrador')], default='estudiante', max_length=50),
        ),
    ]
