# Generated by Django 5.2.3 on 2025-08-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_students_deleted_at_students_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='progenitor_document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
