# Generated by Django 5.2.3 on 2025-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_person_progenitor_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.AddField(
            model_name='person',
            name='pais_origen',
            field=models.CharField(blank=True, choices=[('Venezuela', 'Venezuela'), ('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('República Dominicana', 'República Dominicana'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('España', 'España'), ('Estados Unidos', 'Estados Unidos'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Puerto Rico', 'Puerto Rico'), ('Uruguay', 'Uruguay'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='País de origen'),
        ),
    ]
