# Generated by Django 5.2.3 on 2025-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(error_messages={'unique': 'Ya existe una persona registrada con este número de documento.'}, max_length=20, unique=True),
        ),
    ]
