# Generated by Django 5.2.3 on 2025-09-06 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_person_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='myapp.levels'),
        ),
    ]
