# Generated by Django 5.2.3 on 2025-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_units_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='pdf_material',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
