# Generated by Django 5.2.3 on 2025-09-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_units_pdf_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='units',
            old_name='name',
            new_name='title',
        ),
    ]
