# Generated by Django 5.1.7 on 2025-10-02 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_description_units_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_levels',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AddField(
            model_name='group_levels',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='group_levels',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='cohort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cohorte'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='date_begin',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='date_end',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.levels', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='name_group_levels',
            field=models.CharField(max_length=100, verbose_name='Nombre del grupo'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='group_levels', to='myapp.students', verbose_name='Estudiantes'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='study_modality',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], default='presencial', max_length=50, verbose_name='Modalidad'),
        ),
    ]
