# Generated by Django 5.2.3 on 2025-10-10 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_group_levels_options_group_levels_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_levels',
            options={'verbose_name': 'Grupo Nivel', 'verbose_name_plural': 'Grupos Niveles'},
        ),
        migrations.RemoveField(
            model_name='group_levels',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='group_levels',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='cohort',
            field=models.IntegerField(blank=True, help_text='Cohorte del Grupo', null=True),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='date_begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.levels'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='name_group_levels',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='group_levels', to='myapp.students'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='study_modality',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], default='presential', max_length=50),
        ),
    ]
