# Generated by Django 5.2.3 on 2025-10-11 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_add_tipo_evaluacion_to_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade_students',
            name='evaluacion',
            field=models.ForeignKey(blank=True, help_text='Evaluación asociada a esta nota', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.testing', verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='grade_students',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='grade_students',
            unique_together={('student', 'evaluacion')},
        ),
    ]
