# Generated by Django 5.2.3 on 2025-11-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_testing_tipo_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='tipo_evaluacion',
            field=models.CharField(choices=[('examen', 'Examen'), ('quiz', 'Quiz'), ('tarea', 'Tarea'), ('proyecto', 'Proyecto'), ('participacion', 'Participación'), ('personalizada', 'Evaluación Personalizada')], default='examen', max_length=50, verbose_name='Tipo de Evaluación'),
        ),
    ]
