# Generated by Django 5.2.3 on 2025-11-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_todoitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Evento Activo'),
        ),
    ]
