# Generated by Django 5.2.3 on 2025-12-24 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_calendario_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'ordering': ['fecha_inicio', 'titulo'], 'verbose_name': 'Evento de calendario', 'verbose_name_plural': 'Eventos de calendario'},
        ),
        migrations.AlterModelOptions(
            name='group_levels',
            options={'ordering': ['-date_begin', 'name_group_levels'], 'verbose_name': 'Grupo Nivel', 'verbose_name_plural': 'Grupos Niveles'},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={'ordering': ['course', 'level_name'], 'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='testing',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-priority', 'due_date', '-created_at'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'ordering': ['level', 'topic_order'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='calendario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='grade_students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade_students',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='grade_students',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='grade_students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='group_levels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_levels',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='group_levels',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='group_levels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='levels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='testing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='testing',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='testing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='units',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='units',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='units',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='units',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='group_levels',
            name='study_modality',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], default='presencial', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Ya existe una persona registrada con este email.'}, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='group_levels',
            unique_together={('name_group_levels', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='levels',
            unique_together={('level_name', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='units',
            unique_together={('level', 'topic_order')},
        ),
        migrations.AddIndex(
            model_name='calendario',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='calendario_fecha_i_bdb298_idx'),
        ),
        migrations.AddIndex(
            model_name='calendario',
            index=models.Index(fields=['creador', 'activo'], name='calendario_creador_5f46bf_idx'),
        ),
        migrations.AddIndex(
            model_name='calendario',
            index=models.Index(fields=['activo', 'fecha_inicio'], name='calendario_activo_6f6f18_idx'),
        ),
        migrations.AddIndex(
            model_name='grade_students',
            index=models.Index(fields=['student', 'evaluacion'], name='notas_estud_student_f5eae6_idx'),
        ),
        migrations.AddIndex(
            model_name='grade_students',
            index=models.Index(fields=['group_level', 'created_at'], name='notas_estud_group_l_379967_idx'),
        ),
        migrations.AddIndex(
            model_name='group_levels',
            index=models.Index(fields=['level', 'date_begin'], name='grupos_nive_level_i_6bf762_idx'),
        ),
        migrations.AddIndex(
            model_name='group_levels',
            index=models.Index(fields=['study_modality', 'cohort'], name='grupos_nive_study_m_3ea687_idx'),
        ),
        migrations.AddIndex(
            model_name='group_levels',
            index=models.Index(fields=['date_begin', 'date_end'], name='grupos_nive_date_be_f84412_idx'),
        ),
        migrations.AddIndex(
            model_name='levels',
            index=models.Index(fields=['course', 'level_name'], name='niveles_course__0c2ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='levels',
            index=models.Index(fields=['duration'], name='niveles_duratio_92f9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['document_number'], name='personas_documen_a34761_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='personas_email_af4c81_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name', 'surname'], name='personas_name_6f1f60_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['type_document', 'document_number'], name='personas_type_do_4eb259_idx'),
        ),
        migrations.AddIndex(
            model_name='testing',
            index=models.Index(fields=['group_level', 'date'], name='evaluacione_group_l_95acbd_idx'),
        ),
        migrations.AddIndex(
            model_name='testing',
            index=models.Index(fields=['tipo_evaluacion', 'date'], name='evaluacione_tipo_ev_376ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='testing',
            index=models.Index(fields=['student', 'group_level'], name='evaluacione_student_5c6502_idx'),
        ),
        migrations.AddIndex(
            model_name='testing',
            index=models.Index(fields=['name', 'group_level'], name='evaluacione_name_64b98a_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', 'completed'], name='tareas_user_id_3fbe1a_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['due_date', 'priority'], name='tareas_due_dat_b0d7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['created_at'], name='tareas_created_c184da_idx'),
        ),
        migrations.AddIndex(
            model_name='units',
            index=models.Index(fields=['level', 'topic_order'], name='unidades_level_i_63a3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='units',
            index=models.Index(fields=['title'], name='unidades_title_662675_idx'),
        ),
    ]
